### ISSUE TITLE
Widget for Native Mobile

### ISSUE THREAD

**Issue by webfryslan** [nathan-JJRplus/EZWebsocket#1]
Is it possible to incude a widget for native mobile?

**Comment by nathan-JJRplus** [comment]
Hi Webfryslan, I was actually considering adding this, but now I know that there is actually some demand for it I'll move it up my backlog 😁

**Comment by webfryslan** [comment]
Great, if you need a tester, I 'am in.  
regards,  
Martin

**Comment by nathan-JJRplus** [comment]
Thanks! I'll keep you posted

**Comment by nathan-JJRplus** [comment]
Hi webfryslan,

I added the native client widget in the new version 1.3.0 😁
Find it here: 
https://marketplace.mendix.com/link/component/205276
