### ISSUE TITLE
New feature: add a message 

### ISSUE THREAD

**Issue by Lionel1712** [nathan-JJRplus/EZWebsocket#2]
Hi,
it would be perfect if we could also provide a message added to the action keyword.

**Comment by nathan-JJRplus** [comment]
Hi Lionel, thanks for your feature request.

What is it exactly you are trying to achieve, which does not seem to be possible in the module's current form?
Where do you want to include a message and how should the client handle this?

**Comment by Lionel1712** [comment]
Hi,
i have a complex object i want to sync between several user sessions and
API updates.
So when an update is made, i want to send to all user sessions the
information that an update has been made and a message explaining the
update content.

On the user session, when an update notification is received i want to
display an update button that displays the message (what has been updated)
and gives the opportunity to refresh content.

Lionel


Le lun. 6 mars 2023 à 16:56, Nathan Ruth ***@***.***> a
écrit :

**Comment by nathan-JJRplus** [comment]
Hi Lionel,

It sounds like you should be able to handle this within Mendix.

You can create a non-persistent entity with a boolean to show/hide the button and a string for the message, this can be passed to the update logic along with the complex object and you can then update accordingly.

The update message can either be generated client-side inside your update logic or stored within the complex object and then copied to the new NPE.

How does this sound?

**Comment by Lionel1712** [comment]
The show/hide is not a problem.
I dont want to store the message on my complex object because:
1. it can be updated at the same time by several sessions and it would lead
to a concurrent access issue
2. the message concerns a process and not the object itself, so i dont want
to store it.

is it clearer ?

Cordialement

Lionel LUQUET


Le lun. 6 mars 2023 à 17:19, Nathan Ruth ***@***.***> a
écrit :

**Comment by nathan-JJRplus** [comment]
Hi Lionel, 

I see that sending a message would be an interesting feature. 
I have some ideas about the implementation and will try to add it over the weekend, I'll keep you updated!

**Comment by Lionel1712** [comment]
Great, thanks !

Lionel


Le mar. 7 mars 2023 à 10:57, Nathan Ruth ***@***.***> a
écrit :

**Comment by nathan-JJRplus** [comment]
Hi Lionel,
Check out v1.4.0 and let me know what you think! 😁

**Comment by Lionel1712** [comment]
Hi,
i have just seen the release notes and that seems promising!

I have moved on other tasks, but i'll let you know as soon as i have tested
it!

Thx

Lionel


Le sam. 11 mars 2023 à 17:35, Nathan Ruth ***@***.***> a
écrit :

**Comment by nathan-JJRplus** [comment]
Hi Lionel, have you been able to successfully implement the message feature yet?

**Comment by Lionel1712** [comment]
Hi, sorry for the delay, i have been busy on other topics.
I have tested and it works.

I dont know if there is a limitation, but the message received can only be stored in a persisted entity. It would be nice to be able to store it in a NPE.

Thx for the new feature !
