### ISSUE TITLE
Multi-Instance Support?

### ISSUE THREAD

**Issue by psilordOG** [nathan-JJRplus/EZWebsocket#3]
Hi, great module.  So far I've only tested locally in Studio Pro but really need support for multiple instances in a production environment. I noticed your documentation indicates no support for multi-instance yet.  What are the issues found when scaling an app to several instances and are there any plans to support this?

**Comment by nathan-JJRplus** [comment]
Hi Psilord,

I haven't actually tested this in a multi-instance environment, but I think we can assume it would not always work properly.

The reason for this is that the subscriptions are managed in memory. This means that when you want to publish a message to all subscribers of a certain object, these subscribers could be spread out over multiple instances, and depending on from where the notify action gets called it might only notify a sub-group of subscribers depending on which instance is handling the notify action.

In order to fix this I would have to store the subscriptiondata in the db instead, this will however (slighly) increase response times.

I've been putting this off until someone would ask about it, so I guess its time to do something now 😁

**Comment by psilordOG** [comment]
Hi Nathan,

Thanks for the explanation.  One of my primary use cases is to provide the current system date and time to clients updated in realtime every second.  We have some processes that need to be triggered on the client based on precise server time and I cannot rely on the client / device timeclock.  All of the widgets I have found that trigger an action based on a timer or countdown utilize the client's device time which is easily manipulated.

So far I have managed to use your module to implement a websocket that updates a realtime clock on the clients page every second.  I initialize the websocket in the after startup microflow and immediately spawn a notify microflow in a task queue that is limited in scope to 1 thread cluster-wide.  The notify microflow waits 1 second, executes the JA_Notify action instructing the clients to refresh, and then respawns itself using the same task queue.  I haven't tested it in my QA cluster using multiple instances yet, but I will today and let you know what I find.  All of our environments are on-premise so we have a good deal more control and visibility as to their configuration and inner workings.

**Comment by nathan-JJRplus** [comment]
Thanks for sharing your usecase! I will be awaiting your findings 😁

**Comment by nathan-JJRplus** [comment]
Hi Psilord, 
I've been researching a solution during the weekend, and it seems like there is no other way to tackle this than to implement some sort of pub/sub mechanism. This means I will have to use either an external message broker like redis/kafka, or if I want to keep it pure mendix we will need to use their business events functionality, but this doesn't support on-premise yet and comes at a cost.

I'm not sure how to continue yet, and I'll keep researching, but if you have any ideas let me know!

**Comment by psilordOG** [comment]
Hi Nathan,

I was finally able to deploy our application to our on-premises QA environment and scaled it to four instances.  Surprisingly, the real time clock feature that I implemented with EZ Websocket continues working, even when the browser is refreshed and the request is handled by a different application pod as indicated by the XASID client cookie.

I did need to change the configuration of the task queue that I use to execute the notify action MF from 1 thread cluster-wide to 1-thread per node.  I have yet to test it under load with several hundred or more users, but I suspect that when the page is reloaded, whichever instance responds to the request adds the client to it's in-memory EZ Websocket subscription list so it continues getting notified...  ?  

Since the notify MF is spawned after startup, each instance is executing it in it's own single thread task queue, and subsequently re-spawns itself as it's last step.  I need to take a deeper dive into the Mendix Task Queue implementation to see if the re-spawned tasks ever end up getting scheduled in a different instances task queue.  I'm not terribly familiar with how task queue scheduling works in a multi-instance environment.

I definitely need a solution that works in an on-premise environment and prefer to not use non-Mendix components if possible.  I wonder if Mendix has any sort of inter-instance communication strategy that can be leveraged to replicate subscriptions between instances without relying on storing them in a database.  Inter-instance REST or websockets between nodes?  It would probably need to be orchestrated by the master worker node/instance, similar to how DDL changes are centrally managed by the master during application startup.  Hmm...

Mick

**Comment by psilordOG** [comment]
While the above is working as a prototype solution for this specific use case, I am concerned that my using task queues for this purpose will be more overhead in a production environment than is desirable.  Task queue logs are heavily impacted, and task scheduling may be prone to glitchy behavior in the event the task scheduler in Mendix might skip or miss picking up it's next task on an available node from time to time.  I plan to test it under load in a simple implementation to gauge how it behaves.

If I had the ability in Mendix to configure a different logging level per task queue, that would solve my first problem.  Unfortunately, since Mendix does not allow targeting the task being scheduled to only the XASID instance that spawned it, locality cannot be guaranteed.  

I will reach out to them and inquire if they might consider as enhancements:  1) Ability to specify the log level for a specific task queue, and 2) a boolean option when scheduling a MF or JA to run in a task queue that would restrict it from being picked up by an instance that it was not spawned from.

**Comment by nathan-JJRplus** [comment]
Hi Mick, I noticed some more discussions surrounding the module mention multi instance so I decided to add it as a separate module

https://marketplace.mendix.com/link/component/227663
