### ISSUE TITLE
v.1.4.1 Not Working

### ISSUE THREAD

**Issue by psilordOG** [nathan-JJRplus/EZWebsocket#5]
v.1.4.1 breaks the widget loading. No console errors are generated, the widget simply does not load. Running modeler v9.24.16.

**Comment by nathan-JJRplus** [comment]
Hi Mick thanks for making this issue, I saw your review just now

this seems like a weird issue. The only thing I changed was that the widget now waits for the messageAttribute to initialize.

That's this line of code in the useEffect logic
!messageAttribute || messageAttribute.status === "available"

Do you happen to have configured a messageattribute which is not available to the widget?

**Comment by psilordOG** [comment]
I use a NPE for the message attribute.  A dataview with a nanoflow creates the NPE and returns it to the page.  Within the dataview a snippet loads the websocket client widget.  I have an update action defined which also calls a nanoflow to change other attributes on the NPE, which are displayed on the page.

I'll take a look at the java code you mentioned.  I can try to remove the new logic that checks if the messageAttribute and onCloseMicroflowParameterValue exist or are available.

**Comment by psilordOG** [comment]
Unfortunately, I am unable to locate the _!messageAttribute || messageAttribute.status === "available"_ line in the downloaded 1.4.1 module.  I see it in the code in the repo, but not in the 1.4.1 file downloaded from the marketplace.  (Java is not my jam)

**Comment by psilordOG** [comment]
Our mistake!  One of our developers changed a constant in our local modeler profile(s) that disabled the loading of the client widget.

**Comment by nathan-JJRplus** [comment]
Glad you got it figured out! 😄
