### ISSUE TITLE
Websocket Closing After 1 Minute

### ISSUE THREAD

**Issue by BWeinbergImpact** [nathan-JJRplus/EZWebsocket#6]
First, I love this module thank you for making the Mendix Websockets as easy as possible.

On deployment of our application, the websocket is closing after one minute exactly. I have set to 0 timeout time on the startup of the websocket but it is still closing. I only have this issue when deployed (both on Mx Cloud and Mx4PC) when running locally it stays connected. 

Any help would be appreciated!

**Comment by nathan-JJRplus** [comment]
Hi BWeinbergImpact,

This is the first time Im hearing about this.
Do you have the KeepAlive setting turned off or do you have specific changes in runtime settings surrounding sessions?

https://docs.mendix.com/refguide/custom-settings/#web-client-settings

**Comment by BWeinbergImpact** [comment]
I created a new application, downloaded ez websockets, copied the way the test application was setup, and deployed it to Mendix free app. It still closes after 1 minute. This is using the latest published version to the marketplace using 10.12.2 (my app is running 9.24.24)

https://testwebsockets102-sandbox.mxapps.io/ (click the counter nav option)

![image](https://github.com/user-attachments/assets/ba0a24ac-7c8e-42e9-a748-f3e179e99e60)

**Comment by nathan-JJRplus** [comment]
Thanks for showing me, I have no idea how noone (including me) noticed this before.
It seems like there is some sort of server configuration which cleans up idle connections.

I will use the coming week to implement a keepalive mechanism, which I expect to publish next sunday.

**Comment by BWeinbergImpact** [comment]
Awesome, thank you!

Is it possible to get a backport of that fix for Mx 9 LTS (9.24.25) when you get it fixed?

**Comment by nathan-JJRplus** [comment]
I've been working on some necessary refactoring, and I'm happy to report that I've succesfully implemented the keepalive mechanism. There are still a few final details and some configurability options that I want to include before publishing the final results to the marketplace, so it will take a little longer to get it out.

If you're interested, check out the latest commit for a preview

**Comment by nathan-JJRplus** [comment]
> Awesome, thank you!
> 
> Is it possible to get a backport of that fix for Mx 9 LTS (9.24.25) when you get it fixed?

If there more demand for it I might consider

**Comment by nathan-JJRplus** [comment]
Small update, finished all the devwork, improved DX experience now that sessionTimeout is irrelevant for most usecases
Tested on free tier mendix cloud and looks like its working as expected 😄 

Also switched sending literal "ping" and "pong" strings down the line for the built-in websocket protocol ping and pongs, so that they won't clog up your devconsole traffic

Because I've changed up the whole thing I need to update the docs, after that I will publish

**Comment by nathan-JJRplus** [comment]
Just published the new version, with proper keepalive mechanism, 
enjoy, and thanks for helping me make the module even better! 😄

https://marketplace.mendix.com/link/component/205276

**Comment by BWeinbergImpact** [comment]
Thank you for the quick turnaround!
